unsupervised : false
  
default_model_config:
  context_window_sec : 1
  min_samples_split : 2
  class_weight : balanced
  normalize: False
  wavelet_transform: False
  feature_set: nathan2012
  morlet_w: 10.
  n_wavelets: 25
  downsample: 0
  downsizing_factor: 1
  batch_size: 1000
  num_workers: 4
  