dataset_dir: /home/jupyter/bebe_data/baglione_crows
experiment_name: fold_1
final_model_dir: /home/jupyter/behavior_benchmarks_experiments/baglione_crows_CNN_hyperparameter_selection/CNN_hyperparameter_selection_24/final_model
input_vars:
- AccX
- AccY
- AccZ
metadata:
  clip_column_names:
  - AccX
  - AccY
  - AccZ
  - individual_id
  - label
  clip_id_to_individual_id:
    19_AL_Azul_07: 0
    19_AL_Naranja_03: 1
    19_AL_Naranja_10: 1
    19_AL_Rosa_13: 2
    19_AL_Rosa_24: 2
    19_BA_Amarilla_06: 3
    19_BA_Amarilla_13: 3
    19_BD_Rosa_03: 4
    19_BPBO_Azul_13: 5
    19_BV_Azul_21: 6
    19_BV_Azul_25: 6
    19_BV_Morado_11: 7
    19_BV_Morado_12: 7
    19_CV_azul_33: 8
    19_EB_Rojo_12: 9
    19_EB_Rojo_15: 9
    19_EB_Rojo_26: 9
    19_EB_Verde_12: 10
    19_EB_Verde_21: 10
    19_EB_Verde_28: 10
  clip_ids:
  - 19_AL_Azul_07
  - 19_AL_Naranja_03
  - 19_AL_Naranja_10
  - 19_AL_Rosa_13
  - 19_AL_Rosa_24
  - 19_BA_Amarilla_06
  - 19_BA_Amarilla_13
  - 19_BD_Rosa_03
  - 19_BPBO_Azul_13
  - 19_BV_Azul_21
  - 19_BV_Azul_25
  - 19_BV_Morado_11
  - 19_BV_Morado_12
  - 19_CV_azul_33
  - 19_EB_Rojo_12
  - 19_EB_Rojo_15
  - 19_EB_Rojo_26
  - 19_EB_Verde_12
  - 19_EB_Verde_21
  - 19_EB_Verde_28
  clip_ids_per_fold:
    0:
    - 19_AL_Azul_07
    - 19_BPBO_Azul_13
    - 19_EB_Verde_12
    - 19_EB_Verde_21
    - 19_EB_Verde_28
    1:
    - 19_AL_Naranja_03
    - 19_AL_Naranja_10
    - 19_BV_Azul_21
    - 19_BV_Azul_25
    2:
    - 19_AL_Rosa_13
    - 19_AL_Rosa_24
    - 19_BV_Morado_11
    - 19_BV_Morado_12
    3:
    - 19_BA_Amarilla_06
    - 19_BA_Amarilla_13
    - 19_CV_azul_33
    4:
    - 19_BD_Rosa_03
    - 19_EB_Rojo_12
    - 19_EB_Rojo_15
    - 19_EB_Rojo_26
  dataset_name: baglione_crows
  individual_ids:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  individuals_per_fold:
    0:
    - 0
    - 5
    - 10
    1:
    - 1
    - 6
    2:
    - 2
    - 7
    3:
    - 3
    - 8
    4:
    - 4
    - 9
  label_names:
  - unknown
  - flying
  - in_nest
  mean_dur_sec_by_individual:
    0: 9.027777777777779
    1: 8.692307692307692
    2: 9.693877551020408
    3: 15.543478260869565
    4: 12.321428571428571
    5: 11.833333333333334
    6: 18.098958333333332
    7: 16.74418604651163
    8: 15.681818181818182
    9: 10.581395348837209
    10: 20.272727272727273
  mean_overall_dur_sec: 14.134502923976608
  n_folds: 5
  sr: 50
model: CRNN
model_config:
  batch_size: 32
  blur_scale: 0
  conv_depth: 2
  dilation: 5
  downsizing_factor: 1024
  dropout: 0
  gru_depth: 0
  gru_hidden_size: 64
  hidden_size: 64
  jitter_scale: 0
  ker_size: 7
  lr: 0.01
  n_epochs: 100
  normalize: false
  rescale_param: 0
  sparse_annotations: true
  temporal_window_samples: 2048
  weight_decay: 0
num_clusters: 3
output_dir: /home/jupyter/behavior_benchmarks_experiments/baglione_crows_CNN_hyperparameter_selection/CNN_hyperparameter_selection_24
output_parent_dir: /home/jupyter/behavior_benchmarks_experiments/baglione_crows_CNN
predictions_dir: /home/jupyter/behavior_benchmarks_experiments/baglione_crows_CNN_hyperparameter_selection/CNN_hyperparameter_selection_24/predictions
seed: 1
static_acc_cutoff_freq: 6.4
temp_dir: /home/jupyter/behavior_benchmarks_experiments/baglione_crows_CNN_hyperparameter_selection/CNN_hyperparameter_selection_24/temp
test_data_fp:
- /home/jupyter/bebe_data/baglione_crows/clip_data/19_AL_Azul_07.csv
- /home/jupyter/bebe_data/baglione_crows/clip_data/19_BPBO_Azul_13.csv
- /home/jupyter/bebe_data/baglione_crows/clip_data/19_EB_Verde_12.csv
- /home/jupyter/bebe_data/baglione_crows/clip_data/19_EB_Verde_21.csv
- /home/jupyter/bebe_data/baglione_crows/clip_data/19_EB_Verde_28.csv
test_folds:
- 1
train_data_fp:
- /home/jupyter/bebe_data/baglione_crows/clip_data/19_AL_Naranja_03.csv
- /home/jupyter/bebe_data/baglione_crows/clip_data/19_AL_Naranja_10.csv
- /home/jupyter/bebe_data/baglione_crows/clip_data/19_AL_Rosa_13.csv
- /home/jupyter/bebe_data/baglione_crows/clip_data/19_AL_Rosa_24.csv
- /home/jupyter/bebe_data/baglione_crows/clip_data/19_BA_Amarilla_06.csv
- /home/jupyter/bebe_data/baglione_crows/clip_data/19_BA_Amarilla_13.csv
- /home/jupyter/bebe_data/baglione_crows/clip_data/19_BD_Rosa_03.csv
- /home/jupyter/bebe_data/baglione_crows/clip_data/19_BV_Azul_21.csv
- /home/jupyter/bebe_data/baglione_crows/clip_data/19_BV_Azul_25.csv
- /home/jupyter/bebe_data/baglione_crows/clip_data/19_BV_Morado_11.csv
- /home/jupyter/bebe_data/baglione_crows/clip_data/19_BV_Morado_12.csv
- /home/jupyter/bebe_data/baglione_crows/clip_data/19_CV_azul_33.csv
- /home/jupyter/bebe_data/baglione_crows/clip_data/19_EB_Rojo_12.csv
- /home/jupyter/bebe_data/baglione_crows/clip_data/19_EB_Rojo_15.csv
- /home/jupyter/bebe_data/baglione_crows/clip_data/19_EB_Rojo_26.csv
unsupervised: false
val_data_fp: []
visualization_dir: /home/jupyter/behavior_benchmarks_experiments/baglione_crows_CNN_hyperparameter_selection/CNN_hyperparameter_selection_24/visualizations
