balance_classes: false
dataset_dir: /home/jupyter/behavior_data_local/baglione_crows/
experiment_name: fold_1
final_model_dir: /home/jupyter/behavior_benchmarks_experiments/baglione_crows_wavelet_rf_hyperparameter_selection/wavelet_rf_hyperparameter_selection_2/final_model
input_vars:
- AccX
- AccY
- AccZ
low_data_setting: false
metadata:
  clip_column_names:
  - AccX
  - AccY
  - AccZ
  - individual_id
  - label
  clip_id_to_individual_id:
    19_AL_Azul_07: 0
    19_AL_Naranja_03: 1
    19_AL_Naranja_10: 1
    19_AL_Rosa_13: 2
    19_AL_Rosa_24: 2
    19_BA_Amarilla_06: 3
    19_BA_Amarilla_13: 3
    19_BD_Rosa_03: 4
    19_BPBO_Azul_13: 5
    19_BV_Azul_21: 6
    19_BV_Azul_25: 6
    19_BV_Morado_11: 7
    19_BV_Morado_12: 7
    19_CV_azul_33: 8
    19_EB_Rojo_12: 9
    19_EB_Rojo_15: 9
    19_EB_Rojo_26: 9
    19_EB_Verde_12: 10
    19_EB_Verde_21: 10
    19_EB_Verde_28: 10
  clip_ids:
  - 19_AL_Azul_07
  - 19_AL_Naranja_03
  - 19_AL_Naranja_10
  - 19_AL_Rosa_13
  - 19_AL_Rosa_24
  - 19_BA_Amarilla_06
  - 19_BA_Amarilla_13
  - 19_BD_Rosa_03
  - 19_BPBO_Azul_13
  - 19_BV_Azul_21
  - 19_BV_Azul_25
  - 19_BV_Morado_11
  - 19_BV_Morado_12
  - 19_CV_azul_33
  - 19_EB_Rojo_12
  - 19_EB_Rojo_15
  - 19_EB_Rojo_26
  - 19_EB_Verde_12
  - 19_EB_Verde_21
  - 19_EB_Verde_28
  clip_ids_per_fold:
    0:
    - 19_AL_Azul_07
    - 19_BPBO_Azul_13
    - 19_EB_Verde_12
    - 19_EB_Verde_21
    - 19_EB_Verde_28
    1:
    - 19_AL_Naranja_03
    - 19_AL_Naranja_10
    - 19_BV_Azul_21
    - 19_BV_Azul_25
    2:
    - 19_AL_Rosa_13
    - 19_AL_Rosa_24
    - 19_BV_Morado_11
    - 19_BV_Morado_12
    3:
    - 19_BA_Amarilla_06
    - 19_BA_Amarilla_13
    - 19_CV_azul_33
    4:
    - 19_BD_Rosa_03
    - 19_EB_Rojo_12
    - 19_EB_Rojo_15
    - 19_EB_Rojo_26
  dataset_name: baglione_crows
  individual_ids:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  individuals_per_fold:
    0:
    - 0
    - 5
    - 10
    1:
    - 1
    - 6
    2:
    - 2
    - 7
    3:
    - 3
    - 8
    4:
    - 4
    - 9
  label_names:
  - unknown
  - flying
  - in_nest
  mean_dur_sec_by_individual:
    0: 9.027777777777779
    1: 8.692307692307692
    2: 9.693877551020408
    3: 15.543478260869565
    4: 12.321428571428571
    5: 11.833333333333334
    6: 18.098958333333332
    7: 16.74418604651163
    8: 15.681818181818182
    9: 10.581395348837209
    10: 20.272727272727273
  mean_overall_dur_sec: 14.134502923976608
  n_folds: 5
  sr: 50
model: rf
model_config:
  C_max: 1.0
  C_min: null
  batch_size: 100
  class_weight: balanced
  context_window_sec: 8
  downsample: 0
  downsizing_factor: 1
  feature_set: wavelet
  max_samples: 0.1
  min_samples_split: 2
  morlet_w: 20.0
  n_estimators: 100
  n_jobs: 24
  n_wavelets: 15
  normalize: false
  wavelet_transform: true
  whiten: false
num_clusters: 3
output_dir: /home/jupyter/behavior_benchmarks_experiments/baglione_crows_wavelet_rf_hyperparameter_selection/wavelet_rf_hyperparameter_selection_2
output_parent_dir: /home/jupyter/behavior_benchmarks_experiments/baglione_crows_wavelet_rf
predictions_dir: /home/jupyter/behavior_benchmarks_experiments/baglione_crows_wavelet_rf_hyperparameter_selection/wavelet_rf_hyperparameter_selection_2/predictions
seed: 1
static_acc_cutoff_freq: 0
temp_dir: /home/jupyter/behavior_benchmarks_experiments/baglione_crows_wavelet_rf_hyperparameter_selection/wavelet_rf_hyperparameter_selection_2/temp
test_data_fp:
- /home/jupyter/behavior_data_local/baglione_crows/clip_data/19_AL_Azul_07.csv
- /home/jupyter/behavior_data_local/baglione_crows/clip_data/19_BPBO_Azul_13.csv
- /home/jupyter/behavior_data_local/baglione_crows/clip_data/19_EB_Verde_12.csv
- /home/jupyter/behavior_data_local/baglione_crows/clip_data/19_EB_Verde_21.csv
- /home/jupyter/behavior_data_local/baglione_crows/clip_data/19_EB_Verde_28.csv
test_folds:
- 1
train_data_fp:
- /home/jupyter/behavior_data_local/baglione_crows/clip_data/19_AL_Naranja_03.csv
- /home/jupyter/behavior_data_local/baglione_crows/clip_data/19_AL_Naranja_10.csv
- /home/jupyter/behavior_data_local/baglione_crows/clip_data/19_AL_Rosa_13.csv
- /home/jupyter/behavior_data_local/baglione_crows/clip_data/19_AL_Rosa_24.csv
- /home/jupyter/behavior_data_local/baglione_crows/clip_data/19_BA_Amarilla_06.csv
- /home/jupyter/behavior_data_local/baglione_crows/clip_data/19_BA_Amarilla_13.csv
- /home/jupyter/behavior_data_local/baglione_crows/clip_data/19_BD_Rosa_03.csv
- /home/jupyter/behavior_data_local/baglione_crows/clip_data/19_BV_Azul_21.csv
- /home/jupyter/behavior_data_local/baglione_crows/clip_data/19_BV_Azul_25.csv
- /home/jupyter/behavior_data_local/baglione_crows/clip_data/19_BV_Morado_11.csv
- /home/jupyter/behavior_data_local/baglione_crows/clip_data/19_BV_Morado_12.csv
- /home/jupyter/behavior_data_local/baglione_crows/clip_data/19_CV_azul_33.csv
- /home/jupyter/behavior_data_local/baglione_crows/clip_data/19_EB_Rojo_12.csv
- /home/jupyter/behavior_data_local/baglione_crows/clip_data/19_EB_Rojo_15.csv
- /home/jupyter/behavior_data_local/baglione_crows/clip_data/19_EB_Rojo_26.csv
unsupervised: false
val_data_fp: []
visualization_dir: /home/jupyter/behavior_benchmarks_experiments/baglione_crows_wavelet_rf_hyperparameter_selection/wavelet_rf_hyperparameter_selection_2/visualizations
