experiment_name: iic
model: iic
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/HAR
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/HAR

test_folds : 
- 0
seed : 0
static_acc_cutoff_freq : 1.
  
iic_config:
  downsizing_factor : 128
  lr : 0.001
  weight_decay : 0
  n_epochs : 100
  hidden_size : 64
  temporal_window_samples : 2048
  batch_size : 32
  dropout : 0
  jitter_scale : 0
  blur_scale : 0
  context_window_samples : 11
  conv_depth : 2
  ker_size : 7
  dilation : 3
  n_heads : 1
