dataset_dir: /home/jupyter/behavior_data_local/data/formatted/HAR/
experiment_name: vame_test
model: vame
model_config:
  batch_size: 512
  beta: 0
  downsizing_factor: 50
  kmeans_lambda: 0.1
  learning_rate: 0.001
  n_train_steps: 1000
  prediction_decoder: 1
  scheduler: 1
  scheduler_gamma: 0.2
  scheduler_step_size: 100
  time_window_sec: 3
  zdims: 20
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/HAR_vame
seed: 0
static_acc_cutoff_freq: 0
test_folds:
- 0
