dataset_dir: /home/jupyter/behavior_data_local/data/formatted/pagano_bears
experiment_name: hubert_motion_nonorm
model: hubert_motion
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/bears

input_vars : 
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ

use_val_in_train: true

hubert_motion_config:
  batch_size: 32
  downsizing_factor: 5000
  lr: 0.00001
  n_epochs: 50
  sparse_annotations: True
  temporal_window_samples: 10000
  weight_decay: 0
  model_path : /home/jupyter/hubert_motion/models/beartest_nonorm/checkpoints/checkpoint_last.pt
  unfreeze_encoder : -1
  normalize : False
  