dataset_dir: /home/jupyter/behavior_data_local/data/formatted/HAR
experiment_name: example_hmm
model: hmm
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/HAR
test_folds : 
- 0
seed : 0
static_acc_cutoff_freq : 1.

model_config:
  time_bins: 2048
  N_iters: 5
  covariance: diagonal
  matrix_concentration: 1.1
  mean_concentration: 0.1
  cov_scale: 0.1
  cov_df: 0.1
  cov_concentration: 0.1
  cov_scale: 0.1
  wavelet_transform : true
  morlet_w : 5.0
  n_wavelets : 25
  downsample : 1