experiment_name: iic
model: iic
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/whales
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/friedlaender_whales
  
iic_config:
  batch_size: 128
  blur_scale: 0
  context_window_samples: 51
  context_window_stride: 1
  diversity_alpha: 20.0
  downsample_rate: 1
  downsizing_factor: 256
  dropout: 0
  feature_expansion_factor: 1
  hidden_size: 32
  individualized_head: false
  jitter_scale: 0
  lr: 0.0001
  max_iter_gmm: 500
  n_epochs: 1000
  n_pseudolabels: 50
  num_layers: 4
  per_frame_model: gmm
  pseudolabel_dir: /home/jupyter/behavior_benchmarks_outputs/HAR/gmm/predictions
  rescale_param: 0
  state_size: 64
  tau_decay_rate: 0.99
  tau_init: 2.0
  temporal_window_samples: 2048
  weight_decay: 0
