experiment_name: vame
model: vame
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/ladds_seals
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/ladds_seals

vame_config:
  batch_size : 256
  max_epochs : 20
  beta: 0 
  zdims: 10
  learning_rate : 0.0005
  time_window_sec: 1.0
  prediction_sec: 1.0
  kmeans_lambda: 0.1
