experiment_name: gmm
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/HAR
model: gmm
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/HAR
test_folds : 
- 0
seed : 0
static_acc_cutoff_freq : 0

gmm_config:
  max_iter: 150
  n_init: 1