experiment_name: vame
input_vars:
- AccX
- AccY
- AccZ
model: vame
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/rattlesnakes
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/desantis_rattlesnakes
num_clusters: 20
read_latents: True
data_latents_fp_glob: 
- /home/jupyter/behavior_benchmarks_outputs/rattlesnakes/whiten/latents/*.csv

vame_config:
  batch_size : 256
  max_epochs : 100
  beta: 1
  zdims: 10
  learning_rate : 0.0005
  time_window_sec: 16.0
  prediction_sec: 16.0
  kmeans_lambda: 0.1
  downsizing_factor : 4
