experiment_name: gmm
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/HAR
model: gmm
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/HAR

gmm_config:
  max_iter: 150
  n_init: 1