dataset_dir: /home/jupyter/behavior_data_local/data/formatted/vehkaoja_dogs
experiment_name: special_optimizer
model: sashimi
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/dogs
sashimi_config:
  batch_size: 512
  downsizing_factor: 1024
  expand: 1
  ff: 1
  hidden_size: 16
  lr: 0.005
  n_epochs: 100
  n_layers: 2
  pool:
  - 4
  - 4
  sparse_annotations: false
  temporal_window_samples: 2048
  weight_decay: 0
use_val_in_train: true
