experiment_name: kmeans
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- GyrX
- GyrY
- GyrZ
model: kmeans
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/HAR
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/HAR
num_clusters: 24
read_latents: False
# data_latents_fp_glob: 
# - /home/jupyter/behavior_benchmarks_outputs/HAR/whiten_humans/latents/*.npy
