experiment_name: iic_simple
model: iic
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/dogs
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/vehkaoja_dogs
  
iic_config:
  batch_size: 64
  blur_scale: 0
  context_window_samples: 51
  conv_depth: 8
  dilation: 2
  downsizing_factor: 2048
  dropout: 0
  hidden_size: 64
  jitter_scale: 0
  ker_size: 7
  lr: 0.001
  n_epochs: 100
  temporal_window_samples: 4096
  weight_decay: 0