experiment_name: kmeans
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- Depth
model: kmeans
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/ladds_seals
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/ladds_seals
num_clusters: 8
read_latents: True
data_latents_fp_glob: 
- /home/jupyter/behavior_benchmarks_outputs/ladds_seals/whiten_seals/latents/*.npy
  
evaluation:
  boundary_tolerance_sec: 1.0
