experiment_name: gmm
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/maekawa_gulls
model: gmm
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/maekawa_gulls

gmm_config:
  max_iter: 500
  n_init: 1
