dataset_dir: /home/jupyter/behavior_data_local/data/formatted/desantis_rattlesnakes
experiment_name: sashimi
model: sashimi
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/rattlesnakes
sashimi_config:
  batch_size: 8
  downsizing_factor: 32
  dropout: 0
  expand: 1
  ff: 2
  hidden_size: 8
  lr: 0.01
  n_epochs: 10
  n_layers: 3
  pool:
  - 1
  - 2
  sparse_annotations: false
  temporal_window_samples: 64
  weight_decay: 0
use_val_in_train: true
