experiment_name: umapper
input_vars:
- AccX
- AccY
- AccZ
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/desantis_rattlesnakes
model: umapper
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/rattlesnakes
num_clusters: 20

umapper_config:
  morlet_w : 1.
  n_wavelets : 10
  n_neighbors : 16
  min_dist : 0.1
  downsample : 8
  low_freq_cols : []
  