experiment_name: rf_per_sample
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- GyrX
- GyrY
- GyrZ
model: rf
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/HAR
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/HAR
num_clusters: 8
 
  
read_latents: false
rf_config:
  n_samples_window : 16
  min_samples_split : 2
  max_samples : 0.25
  n_jobs : 4
  n_estimators : 100
  

