experiment_name: CRNN
input_vars:
- AccX
- AccY
- AccZ
model: CRNN
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/rattlesnakes
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/desantis_rattlesnakes
num_clusters: 4
  
read_latents: false
CRNN_config:
  downsizing_factor : 16
  lr : 0.001
  weight_decay : 0.001
  n_epochs : 100
  hidden_size : 64
  temporal_window_samples : 64
  batch_size : 64
  dropout : 0
  rescale_param : 0
  jitter_scale : 0
  blur_scale : 0
  conv_depth : 2
  weight_factor : 0.5
  sparse_annotations : False
  ker_size : 7
  dilation : 1
  gru_depth : 1
  gru_hidden_size : 32

