experiment_name: vame
model: vame
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/rattlesnakes
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/desantis_rattlesnakes

vame_config:
  batch_size : 256
  max_epochs : 50
  beta: 1
  zdims: 10
  learning_rate : 0.0005
  time_window_sec: 16.0
  prediction_sec: 16.0
  kmeans_lambda: 0.1
  downsizing_factor : 4
