experiment_name: wicc_seals_hmm
model: wicc
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/ladds_seals
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/ladds_seals

input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- Depth
  
wicc_config:
  batch_size: 128
  blur_scale: 0
  context_window_samples: 25
  context_window_stride: 1
  diversity_alpha: 2.0
  downsample_rate: 2
  downsizing_factor: 64
  dropout: 0
  feature_expansion_factor: 1
  hidden_size: 32
  individualized_head: true
  jitter_scale: 0
  lr: 0.001
  max_iter_gmm: 500
  n_epochs: 100
  n_pseudolabels: 50
  num_layers: 2
  per_frame_model: gmm
  pseudolabel_dir: /home/jupyter/behavior_benchmarks_outputs/ladds_seals/wicc_seals_pooling/pseudolabels
  # psuedolabel_dir: null
  rescale_param: 0
  state_size: 64
  tau_decay_rate: 0.985
  tau_init: 2.0
  temporal_window_samples: 512
  weight_decay: 0