experiment_name: kmeans
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/maekawa_gulls
model: kmeans
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/maekawa_gulls
num_clusters: 20

kmeans_config:
  max_iter: 500
  n_init: 1
