experiment_name: rf
input_vars:
- AccX
- AccY
- AccZ
model: rf
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/desantis_rattlesnakes
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/desantis_rattlesnakes
num_clusters: 8
  
rf_config:
  context_window_sec : 1
  min_samples_split : 2
  max_samples : 0.1
  n_jobs : 1
  n_estimators : 100
