experiment_name: CRNN
model: CRNN
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/HAR
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/HAR

CRNN_config:
  downsizing_factor : 1024
  lr : 0.01
  weight_decay : 0.001
  n_epochs : 100
  hidden_size : 64
  temporal_window_samples : 512 
  batch_size : 2048
  conv_depth : 2
  sparse_annotations : false
  ker_size : 7
  dilation : 1
  gru_depth : 1
  gru_hidden_size : 32