experiment_name: whiten_humans
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- GyrX
- GyrY
- GyrZ
model: whiten
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/HAR
num_clusters: 24
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/HAR
  
evaluation:
  boundary_tolerance_sec: 0.5
