experiment_name: hmm
model: hmm
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/desantis_rattlesnakes
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/desantis_rattlesnakes
  
hmm_config:
  time_bins : 2500
  prior_wait_sec : 5.
  sticky_prior_strength : 0.
  N_iters : 50
  lags : 1