experiment_name: whiten_squirrels
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/studd_squirrels
model: whiten
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/studd_squirrels
num_clusters: 20
  
evaluation:
  boundary_tolerance_sec: 0.5
