experiment_name: rf
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- Depth
model: rf
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/ladds_seals
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/ladds_seals
num_clusters: 8
  
rf_config:
  n_samples_window : 16
  min_samples_split : 2
  max_samples : 0.1
  n_jobs : 1
  n_estimators : 100
