experiment_name: hmm
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- Depth
model: hmm
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/ladds_seals
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/ladds_seals
num_clusters: 8
  
hmm_config:
  time_bins : 2500
  prior_wait_sec : 5.
  sticky_prior_strength : 0.
  N_iters : 50
  lags : 0
