experiment_name: hmm_strong_prior
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- GyrX
- GyrY
- GyrZ
- Depth
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/jeantet_turtles
model: hmm
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/jeantet_turtles
num_clusters: 14
  
evaluation:
  boundary_tolerance_sec: 1.0
  
hmm_config:
  time_bins : 2500
  prior_wait_sec : 5.
  sticky_prior_strength : 3.
  N_iters : 50
  lags : 1
