experiment_name: rf
model: rf
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/ladds_seals
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/ladds_seals
  
rf_config:
  n_samples_window : 16
  min_samples_split : 2
  max_samples : 0.1
  n_jobs : 1
  n_estimators : 100
