experiment_name: vame_csv
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- GyrX
- GyrY
- GyrZ
model: vame
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/HAR
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/HAR
save_latents: True
num_clusters: 24
read_latents: True
data_latents_fp_glob: 
- /home/jupyter/behavior_benchmarks_outputs/HAR/whiten_humans/latents/*.csv
  
evaluation:
  boundary_tolerance_sec: 1.0
  
vame_config:
  batch_size : 256
  max_epochs : 100
  beta: 1
  zdims: 10
  learning_rate : 0.0005
  time_window_sec: 1.0
  prediction_sec: 1.0
  kmeans_lambda: 0.1
  downsizing_factor : 64
