dataset_dir: /home/jupyter/behavior_data_local/data/formatted/friedlaender_whales
experiment_name: rf
model: rf
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/whales

rf_config:
  n_samples_window : 16
  min_samples_split : 2
  max_samples : 0.1
  n_jobs : 1
  n_estimators : 100
