dataset_dir: /home/jupyter/behavior_data_local/data/formatted/friedlaender_whales
evaluation: {}
experiment_name: kmeans_features
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- Depth
- Speed
- Pitch
- Roll
model: kmeans
num_clusters: 20
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/whales
