experiment_name: sashimi
model: sashimi
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/friedlaender_whales
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/friedlaender_whales
  
sashimi_config:
  batch_size: 64
  blur_scale: 0
  downsizing_factor: 1024
  dropout: 0
  lr: 0.01
  n_epochs: 5
  temporal_window_samples: 2048
  weight_decay: 0
  hidden_size : 16
  n_layers : 4
  pool : 
  - 2
  - 2
  expand : 2
  ff : 2
