experiment_name: rf
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/jeantet_turtles
model: rf
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/jeantet_turtles

rf_config:
  n_samples_window : 16
  min_samples_split : 2
  max_samples : 0.1
  n_jobs : 6
  n_estimators : 100