experiment_name: eskmeans
eskmeans_config:
  boundary_init_lambda: 20.0
  embed_length: 10
  landmark_hop_size: 5
  n_epochs: 10
  n_landmarks_max: 30
  batch_size: 2
  time_power_term: .85
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- GyrX
- GyrY
- GyrZ
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/HAR
model: eskmeans
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/HAR
num_clusters: 20
read_latents: True
data_latents_fp_glob: 
- /home/jupyter/behavior_benchmarks_outputs/HAR/whiten_humans/latents/*.npy

evaluation:
  boundary_tolerance_sec: 0.5