experiment_name: umapper
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- GyrX
- GyrY
- GyrZ
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/HAR
model: umapper
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/HAR
num_clusters: 24

umapper_config:
  n_watershed_trials : 10
  
evaluation:
  boundary_tolerance_sec: 1.0
  