experiment_name: wicc_timing
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- GyrX
- GyrY
- GyrZ
model: wicc
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/HAR
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/HAR
num_clusters: 24
  
evaluation:
  boundary_tolerance_sec: 1.0
  
read_latents: false
wicc_config:
  batch_size: 64
  blur_scale: 0
  context_window_samples: 25
  diversity_alpha: 2.0
  downsample_rate: 2
  downsizing_factor: 256
  dropout: 0
  feature_expansion_factor: 1
  hidden_size: 8
  jitter_scale: 0
  lr: 0.01
  max_iter_gmm: 100
  n_epochs: 15
  num_layers: 2
  rescale_param: 0
  state_size: 64
  tau_decay_rate: 0.975
  tau_init: 2.0
  temporal_window_samples: 2048
  weight_decay: 0
  n_pseudolabels : 24
