experiment_name: gmm
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- Depth
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/ladds_seals
model: gmm
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/ladds_seals
num_clusters: 8

gmm_config:
  max_iter: 100
  n_init: 10
  
evaluation:
  boundary_tolerance_sec: 1.0



# config = {'experiment_name' : 'gmm_test',
#          'model' : 'gmm',
#          'num_components' : 8,
#          'output_parent_dir' : '/home/jupyter/behavior_benchmarks_outputs/jeantet_turtles',
#          'input_vars' : ['AccX',
#                          'AccY',
#                          'AccZ',
#                          'GyrX',
#                          'GyrY',
#                          'GyrZ',
#                          'Depth'], 
#          'metadata_fp' : '/home/jupyter/behavior_data_local/data/formatted/jeantet_turtles/dataset_metadata.yaml',
#          'train_data_fp_glob' : ['/home/jupyter/behavior_data_local/data/formatted/jeantet_turtles/clip_data/*.npy'],
#          'test_data_fp_glob' : ['/home/jupyter/behavior_data_local/data/formatted/jeantet_turtles/clip_data/*.npy']}