experiment_name: kmeans
input_vars:
- AccX_Back 
- AccY_Back
- AccZ_Back
- AccX_Neck
- AccY_Neck
- AccZ_Neck
- StaticAccX_Back 
- StaticAccY_Back
- StaticAccZ_Back
- StaticAccX_Neck
- StaticAccY_Neck
- StaticAccZ_Neck
- GyrX_Back
- GyrY_Back
- GyrZ_Back
- GyrX_Neck
- GyrY_Neck
- GyrZ_Neck
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/vehkaoja_dogs
model: kmeans
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/vehkaoja_dogs
num_clusters: 20
read_latents: True
data_latents_fp_glob: 
- /home/jupyter/behavior_benchmarks_outputs/vehkaoja_dogs/whiten_dogs/latents/*.npy

evaluation:
  boundary_tolerance_sec: 0.5
