experiment_name: supervised_nn0
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- GyrX
- GyrY
- GyrZ
model: supervised_nn
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/HAR
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/HAR
num_clusters: 8
  
evaluation:
  boundary_tolerance_sec: 1.0
  
read_latents: false
supervised_nn_config:
  batch_size: 512
  downsizing_factor: 128
  hidden_size: 8
  lr: 0.01
  n_epochs: 300
  num_layers: 3
  scheduler_epochs_between_step: 100
  temporal_window_samples: 512
  weight_decay: 0.001
  dropout: 0
  blur_scale: 0
  jitter_scale: 0
  rescale_param: 0
  scheduler_patience_epochs : 10
  best_model_patience : 50
  scheduler_decay: 0.5
