experiment_name: whiten_seals
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- Depth
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/ladds_seals
model: whiten
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/ladds_seals
num_clusters: 8
  
evaluation:
  boundary_tolerance_sec: 0.5
