experiment_name: supervised_nn_may18_s4_test_downsampled_twice
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- Depth
- Speed
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/friedlaender_whales
model: supervised_nn
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/friedlaender_whales
num_clusters: 5
  
evaluation:
  boundary_tolerance_sec: 1.0

supervised_nn_config:
  batch_size: 8
  downsizing_factor: 2048
  dropout: 0.
  hidden_size: 8
  lr: 0.001
  n_epochs: 200
  num_layers: 2
  temporal_window_samples: 8196
  weight_decay: 0.001
  blur_scale: 0.02
  jitter_scale: 0
  rescale_param: 0
  sparse_annotations: False
  weight_factor : 0.5
  state_size : 64
