experiment_name: vq_cpc_with_test
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- GyrX
- GyrY
- GyrZ
model: vq_cpc
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/HAR
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/HAR
num_clusters: 24
  
evaluation:
  boundary_tolerance_sec: 1.0
  
read_latents: false

vq_cpc_config:
  batch_size: 64
  blur_scale: 0.0
  c_dim: 16
  conv_stack_depth: 12
  conv_stack_hidden_size: 64
  downsizing_factor: 256
  encoder_kernel_width: 7
  initial_lr: 1.0e-05
  jitter_scale: 0.0
  lr: 0.0004
  n_epochs: 2
  predict_proportion: 0.5
  temporal_window_samples: 1024
  warmup_epochs: 150
  z_dim: 8
  pooling_factor : 32