experiment_name: supervised_nn_conv_stack
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- GyrX
- GyrY
- GyrZs
- Depth
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/jeantet_turtles
model: supervised_nn
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/jeantet_turtles
num_clusters: 14
  
evaluation:
  boundary_tolerance_sec: 1.0

supervised_nn_config:
  batch_size: 512
  downsizing_factor: 1024
  dropout: 0.01
  hidden_size: 8
  lr: 0.01
  n_epochs: 1
  num_layers: 3
  temporal_window_samples: 2048
  weight_decay: 0.001
  blur_scale: 0.02
  jitter_scale: 0.02
  rescale_param: 0
  conv_stack_depth: 3

# config = {'experiment_name' : 'gmm_test',
#          'model' : 'gmm',
#          'num_components' : 8,
#          'output_parent_dir' : '/home/jupyter/behavior_benchmarks_outputs/jeantet_turtles',
#          'input_vars' : ['AccX',
#                          'AccY',
#                          'AccZ',
#                          'GyrX',
#                          'GyrY',
#                          'GyrZ',
#                          'Depth'], 
#          'metadata_fp' : '/home/jupyter/behavior_data_local/data/formatted/jeantet_turtles/dataset_metadata.yaml',
#          'train_data_fp_glob' : ['/home/jupyter/behavior_data_local/data/formatted/jeantet_turtles/clip_data/*.npy'],
#          'test_data_fp_glob' : ['/home/jupyter/behavior_data_local/data/formatted/jeantet_turtles/clip_data/*.npy']}