experiment_name: umapper1
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- GyrX
- GyrY
- GyrZ
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/HAR
model: umapper
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/HAR
num_clusters: 24

umapper_config:
  morlet_w : 1.
  n_wavelets : 10
  n_neighbors : 16
  min_dist : 0.1
  downsample : 8
  low_freq_cols : []
  