experiment_name: supervised_nn_s4_timing
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- GyrX
- GyrY
- GyrZ
model: supervised_nn
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/HAR
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/HAR
num_clusters: 8
  
evaluation:
  boundary_tolerance_sec: 1.0
  
read_latents: false
supervised_nn_config:
  batch_size: 32
  downsizing_factor: 256
  dropout: 0.
  hidden_size: 8
  lr: 0.001
  n_epochs: 150
  num_layers: 2
  temporal_window_samples: 2048
  weight_decay: 0.001
  blur_scale: 0.02
  jitter_scale: 0
  rescale_param: 0
  sparse_annotations: False
  weight_factor : 0.5

