experiment_name: wicc_with_diversity_loss
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- GyrX
- GyrY
- GyrZ
model: wicc
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/HAR
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/HAR
num_clusters: 24
  
evaluation:
  boundary_tolerance_sec: 1.0
  
read_latents: false
wicc_config:
  batch_size: 32
  downsizing_factor: 512
  dropout: 0.
  hidden_size: 8
  lr: 0.01
  n_epochs: 50
  num_layers: 2
  temporal_window_samples: 2048
  weight_decay: 0
  blur_scale: 0
  jitter_scale: 0
  sparse_annotations: False
  context_window_samples : 25
  downsample_rate : 1
  max_iter_gmm : 100
  feature_expansion_factor : 1
  diversity_alpha : 2.0
  tau_decay_rate : .98

