experiment_name: supervised_nn
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- Depth
- Speed
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/friedlaender_whales
model: supervised_nn
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/friedlaender_whales
num_clusters: 6
  
evaluation:
  boundary_tolerance_sec: 1.0

supervised_nn_config:
  batch_size: 64
  downsizing_factor: 1024
  dropout: 0.01
  hidden_size: 32
  lr: 0.01
  n_epochs: 200
  num_layers: 3
  temporal_window_samples: 2048
  weight_decay: 0.0001
  blur_scale: 0
  jitter_scale: 0
  rescale_param: 0
  conv_stack_depth: 48
  sparse_annotations: True
