experiment_name: umapper2
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- GyrX
- GyrY
- GyrZ
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/HAR
model: umapper
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/HAR
num_clusters: 24

umapper_config:
  morlet_w : 1.
  n_neighbors : 16
  min_dist : 0.1
  train_downsample : 4
  
evaluation:
  boundary_tolerance_sec: 1.0
  