experiment_name: supervised_nn_spec_plus_learned_rep
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- GyrX
- GyrY
- GyrZ
model: supervised_nn
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/HAR
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/HAR
num_clusters: 8
  
evaluation:
  boundary_tolerance_sec: 1.0
  
read_latents: false
supervised_nn_config:
  batch_size: 128
  downsizing_factor: 256
  hidden_size: 8
  lr: 0.01
  n_epochs: 20
  num_layers: 1
  temporal_window_samples: 2048
  weight_decay: 0.001
  dropout: 0
  blur_scale: 0
  jitter_scale: 0
  rescale_param: 0
