experiment_name: supervised_nn2
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/pagano_bears
model: supervised_nn
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/pagano_bears
num_clusters: 11
  
evaluation:
  boundary_tolerance_sec: 1.0

supervised_nn_config:
  batch_size: 128
  downsizing_factor: 1024
  dropout: 0.01
  hidden_size: 16
  lr: 0.005
  n_epochs: 300
  num_layers: 3
  temporal_window_samples: 2048
  weight_decay: 0.001
  blur_scale: 0.05
  jitter_scale: 0
  rescale_param: 0
  conv_stack_depth: 16
  sparse_annotations: True
