experiment_name: supervised_nn_convstack
input_vars:
- AccX
- AccY
- AccZ
- StaticAccX
- StaticAccY
- StaticAccZ
- Depth
dataset_dir: /home/jupyter/behavior_data_local/data/formatted/ladds_seals
model: supervised_nn
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/ladds_seals
num_clusters: 8
  
evaluation:
  boundary_tolerance_sec: 1.0

supervised_nn_config:
  batch_size: 512
  downsizing_factor: 1024
  dropout: 0.01
  hidden_size: 8
  lr: 0.01
  n_epochs: 200
  num_layers: 3
  temporal_window_samples: 2048
  weight_decay: 0.001
  blur_scale: 0.05
  jitter_scale: 0.02
  rescale_param: 0
  best_model_patience : 150
  conv_stack_depth: 3
