experiment_name: eskmeans_test1
eskmeans_config:
  boundary_init_lambda: 20.0
  embed_length: 10
  landmark_hop_size: 5
  n_epochs: 6
  n_landmarks_max: 30
  batch_size: 4
input_vars:
- AccX
- AccY
- AccZ
- GyrX
- GyrY
- GyrZ
- Depth
metadata_fp: /home/jupyter/behavior_data_local/data/formatted/jeantet_turtles/dataset_metadata.yaml
model: eskmeans
output_parent_dir: /home/jupyter/behavior_benchmarks_outputs/jeantet_turtles
test_data_fp_glob:
- /home/jupyter/behavior_data_local/data/formatted/jeantet_turtles/clip_data/*.npy
train_data_fp_glob:
- /home/jupyter/behavior_data_local/data/formatted/jeantet_turtles/clip_data/*.npy
num_clusters: 16

evaluation:
  boundary_tolerance_sec: 0.5




# config = {'experiment_name' : 'gmm_test',
#          'model' : 'gmm',
#          'num_components' : 8,
#          'output_parent_dir' : '/home/jupyter/behavior_benchmarks_outputs/jeantet_turtles',
#          'input_vars' : ['AccX',
#                          'AccY',
#                          'AccZ',
#                          'GyrX',
#                          'GyrY',
#                          'GyrZ',
#                          'Depth'], 
#          'metadata_fp' : '/home/jupyter/behavior_data_local/data/formatted/jeantet_turtles/dataset_metadata.yaml',
#          'train_data_fp_glob' : ['/home/jupyter/behavior_data_local/data/formatted/jeantet_turtles/clip_data/*.npy'],
#          'test_data_fp_glob' : ['/home/jupyter/behavior_data_local/data/formatted/jeantet_turtles/clip_data/*.npy']}